* Summary 

This allows deferred loading of images on a page. 

This supports modern browsers with no external dependencies. 

* Usage 


* Notes 


** DONE Baseline performance of setup of the deferred image approach 

Using a parameter-driven approach creates a redirection chain.

http://pagespeed.googlelabs.com/#url=http_3A_2F_2Fwal.sh_2Fpoc_2Fjwimgdeferred_2Favatars__start.html&mobile=false&rule=MinimizeRedirects

Remove the following redirect chain if possible:
http://www.gravatar.com/.../20e4c4c40c1bafc3131f5c1c1236a984?...
http://mediacdn.disqus.com/1312506743/images/noavatar92.png

This resolves in the following manner:

--2011-09-05 08:38:12--  http://www.gravatar.com/avatar/dbb6e309422a96581b6f0c072a66630d?s=92&d=http%3A%2F%2Fmediacdn.disqus.com%2F1312506743%2Fimages%2Fnoavatar92.png
Resolving www.gravatar.com... 72.233.61.123, 72.233.44.61, 72.233.61.125, ...
Connecting to www.gravatar.com|72.233.61.123|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://mediacdn.disqus.com/1312506743/images/noavatar92.png [following]
--2011-09-05 08:38:12--  http://mediacdn.disqus.com/1312506743/images/noavatar92.png
Resolving mediacdn.disqus.com... 96.17.108.160, 96.17.108.123, 96.17.108.90, ...
Connecting to mediacdn.disqus.com|96.17.108.160|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5455 (5.3K) [image/png]

** DONE Validate the use of data attributes rather than redirectors 

http://www.webpagetest.org/result/110905_B4_1GP0X/


First View
(0.507s)		
Repeat View
(0.492s)

This contrasts with the direct src input with 

http://www.webpagetest.org/result/110905_DQ_1GNV0/

First View
(1.361s)		
Repeat View
(1.233s)

** DONE Use local images 

wal.sh%2Fpoc%2Fjwimgdeferred%2Fstatic%2Fimages%2Favatar.png

mediacdn.disqus.com%2F1312506743%2Fimages%2Fnoavatar92.png

** DONE Confirm base selector for images with class support

** DONE Use no namespace or privacy, use hoisting w/o var at top

** DONE [#B] Apply the deferring at the image level rather than delegating 

** DONE Add scroll logging 

http://www.quirksmode.org/dom/events/scroll.html

Compatibility requires attaching at window.

** DONE Just perform a vertical scroll implementation 

scrollY: 103
pageYOffset: 103

When a user scrolls the page a naive implementation will just recheck all of the images we're monitoring, see if they're now in view, and load.

** DONE Add cache support 

** Rerun performance test 

** Compatibility check
